name: test
on: push

jobs:
  check:
    runs-on: ubuntu-latest
    container: golang:1.15
    steps:
      - uses: actions/checkout@v2

      - name: Download dependencies
        run: go mod tidy

      - name: Run Unit Tests
        run: |
          make test
          bash -c '/bin/bash <(curl -s https://codecov.io/bash)'
      - name: Build executable
        run: go build -v .
